export const cuisineAndFood = [
    "western food",
    "grilled",
    "chinese food",
    "seafood",
    "mcdonald",
    "kfc",
    "indian food",
    "subway",
    "french cuisine",
    "japanese food",
    "italian",
    "thai food",
    "sushi",
    "steak",
    "hotpot",
    "cupnoodles",
    "chicken rice",
    "texas chicken",
    "burger king",
    "fried rice",
    "malay cuisine",
    "fried noodles",
    "porridge",
    "bread",
    "korean food",
    "mixed vege rice"
]